### ISSUE TITLE
REST API question

### ISSUE THREAD

**Issue by duelago** [ogiewon/Hubitat#14]
Hello,

I have a wifi led bulb running this firmware:
https://github.com/stelgenhof/AiLight/wiki/REST-API

My question is if it is possible to use your fine work to turn my lamp on and off? 

I can use curl like this to switch the bulb on:
curl -X POST http://192.168.1.2/api/light -H 'API-Key: hinotori' -H 'Content-Type: application/json' -d '{"brightness": 36, "state": "ON"}'

DEBUG from Hubitat:
2019-09-23 11:15:30.198 debugrunCmd hit exception java.net.URISyntaxException: Illegal character in path at index 10: /api/light -H 'API-Key: hinotori' -H 'Content-Type: application/json' -d '{"brightness": 100, "state": "OFF"}' on null

Best regards,
 /David

**Comment by ogiewon** [comment]
I would recommend you take a look at using the sample driver that Hubitat has published in their public GitHub repository.  You may need to tweak it a little bit to issue a POST instead of a GET, but it at least allows for both an ON and an OFF URL to be entered.  My old driver was not really designed to meet your requirements.

https://github.com/hubitat/HubitatPublic/blob/master/examples/drivers/httpGetSwitch.groovy

**Comment by duelago** [comment]
> I would recommend you take a look at using the sample driver that Hubitat has published in their public GitHub repository. You may need to tweak it a little bit to issue a POST instead of a GET, but it at least allows for both an ON and an OFF URL to be entered. My old driver was not really designed to meet your requirements.
> 
> https://github.com/hubitat/HubitatPublic/blob/master/examples/drivers/httpGetSwitch.groovy

Thanks. I will have a look at that driver!
