### ISSUE TITLE
Tile Templates for Logitech Remote

### ISSUE THREAD

**Issue by jimrobillard** [ogiewon/Hubitat#17]
Thanks for the Logitech integration. Works great, but it took a while to figure out which tile to use for a "Play Pandora" activity. Music player would only turn the activity off. A switch will turn it on or off. Is there a better tile that would implement on/off plus volume and track advance?

**Comment by ogiewon** [comment]
The switch tile works best for each Harmony Activity. Controlling volume from the Dashboard is not something that can be implemented very cleanly, since the Harmony Hub has no way of knowing what the absolute volume is of the device you’re attempting to control. That is why your Harmony remote only has volumeUp and volumeDown.  

You can add a Volume Tile and point it at the Parent Device to have basic volume up and down control.  Read the following post where this is described. https://community.hubitat.com/t/release-logitech-harmony-hub-driver-v0-1-20191231/7618/280?u=ogiewon
